name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "5.9"
          - os: macos-14
            swift: "5.9"
          - os: macos-15
            swift: "5.9"
          - os: ubuntu-latest
            swift: "5.9"

    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - uses: actions/checkout@v3

      - name: "swift test"
        run: swift test

      - name: build
        run: swift build -c release

      - name: set binary path
        id: binary-path
        run: echo "binary-path=$(swift build --show-bin-path -c release)/SPX" >> "$GITHUB_OUTPUT"

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: SPX.${{ matrix.os}}
          path: ${{ steps.binary-path.outputs.binary-path }}

      - name: "test: version"
        run: ${{ steps.binary-path.outputs.binary-path }} --version

      - name: "test: help"
        run: ${{ steps.binary-path.outputs.binary-path }} --help

      - name: "test: init"
        run: ${{ steps.binary-path.outputs.binary-path }} --init simple

      - name: "test: add"
        run: ${{ steps.binary-path.outputs.binary-path }} --add date2

      - uses: actions/upload-artifact@v3
        with:
          name: spx-init-${{ matrix.swift }}-${{ matrix.os }}
          path: SPX

      - name: "test: run"
        run: ${{ steps.binary-path.outputs.binary-path }} date2

      - name: "test: build"
        run: ${{ steps.binary-path.outputs.binary-path }} --build

      - name: "reset spx dir"
        run: rm -fr SPX

      - name: "template ios - scaffold"
        run: ${{ steps.binary-path.outputs.binary-path }} -i ios

      - name: "template ios - build"
        run: ${{ steps.binary-path.outputs.binary-path }} --build
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - name: "template ios - generate app icon"
        run: ${{ steps.binary-path.outputs.binary-path }} appicon
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - uses: actions/upload-artifact@v3
        with:
          name: spx-ios-${{ matrix.swift }}-${{ matrix.os }}
          path: |
            SPX
            !.build

      - name: "demo: build container"
        run: cd demos/VaporDemo && $(swift build -c release --package-path ../.. --show-bin-path)/spx docker
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: "demo: update and test"
        run: cd demos/VaporDemo && $(swift build -c release --package-path ../.. --show-bin-path)/spx UpdateAndTest
